### PR TITLE
Save cleared notebooks as target version

### PR DESCRIPTION
**Pull request by tbekolay**
I did this as requested in https://github.com/nengo/nengo/pull/1129 to save all the notebooks as version 3 ... however, the result is not great because whether you set format 3 or 4, all notebooks in the Nengo repo will be changed. I think there's some disparity between what `nbconvert` and `nbformat` are doing and what the actual `notebook` are doing... but yeah, I don't use this script so I don't think it's worth tracking down the disparity. Leaving this here in any case if anyone finds it useful.

### CODE REVIEW

**Comment by jgosmann** [comment]
I would assume it changes all the notebooks only once (i.e. this is idempotent, it doesn't change the notebooks more than once with repeated application)?

**Comment by tbekolay** [comment]
I believe so. I don't think it's worth doing this for all notebooks at the moment, though perhaps when we upgrade them all to v4.

**Comment by Seanny123** [comment]
LGTM.

**Comment by Seanny123** [comment]
Any concerns that need to be addressed before this is merged?

**Comment by jgosmann** [comment]
Added a commit to add a command line argument for the target version. I think this should be merged once that commit gets a LGTM.

**Comment by Seanny123** [comment]
LGTM.

**Pull request merged**
